openapi: 3.0.0
info:
  description: rTag's API Spec
  version: "1.0.0"
  title: rTag API
paths:
  /v1/challenge:
    get:
      description: Return details of a single challenge.
      parameters: 
        - name: challengeId
          required: true
          schema: 
            type: string
      responses: 
        '200':
          description: Detail of single challenges
          content:
            application/json: 
              schema:
                items:
                  type: object
                  properties:
                    id:
                      type: string
                      format: uuid
                    ownerId:
                      type: string
                    created:
                      type: string
                      format: date-time
                    title:
                      type: string
                    desciption:
                      type: string
    post: 
      responses:
        '200':
          description: Create a new challenge
  /v1/challenges:
    get:
      description: Return a list of matching challenges.
      responses: 
        '200':
          description: List of challenges
          content: 
            application/json: 
              schema: 
                items: 
                  type: string
  /v1/player:
    get:
      parameters: 
        - name: playerId
          required: true
          schema: 
            type: string
      responses:
        '200':
          description: Details of a single player
  /v1/players:
    get:
      responses: 
        '200':
          description: List of Players
  /v1/rtag:
    get:
      parameters: 
        - name: rtagId
          required: true
          schema: 
            type: string
      responses: 
        '200':
          description: Details of single rTag
    post: 
      responses:
        '200':
          description: Create a new rTag
  /v1/rtags:
    get:
      responses: 
        '200':
          description: List of rTags
          content: 
            application/json: 
              schema:
                items:
                  type: object
                  properties:
                    id:
                      type: string
                      format: uuid
                    ownerId:
                      type: string
                    title: 
                      type: string
  /v1/votes:
    get:
      description: Get votes for a game object
      responses:
        '200':
          description: Return votes count for game object
          content: 
            application/json: 
              schema: 
                items:
                  type: object
                  properties: 
                    objId:
                      type: string
                    upVoteCount:
                      type: integer
                    downVoteCount:
                      type: integer
                    voteCount:
                      type: integer           
    post:
      description: Add a vote for a game object
      responses:
        '200':
          description: Add a single vote to a game object