openapi: 3.0.0
info:
  description: rTag's API Spec
  version: "1.0.0"
  title: rTag API
paths:
  /v1/game-system:
    get:
      description: Retrieve high-level game system details. There is only one.
      responses:
        '200':
          description: TODO.
          content:
            application/json:
              schema:
                items:
                  type: object
                  properties: {}
    patch: 
      description: Update the game system record.
      responses:
        '200':
          description: TODO.
  /v1/season:
    get:
      description: Game season infomation and operations.
      responses:
        '200':
          description: TODO.
          content:
            application/json:
              schema:
                items:
                  type: object
                  properties: {}
    post: 
      description: Add new season.
      responses:
        '200':
          description: TODO.
    patch: 
      description: Update a season.
      responses:
        '200':
          description: TODO.
  /v1/player:
    get:
      description: Retrieve player infomation.
      responses:
        '200':
          description: TODO.
          content:
            application/json:
              schema:
                items:
                  type: object
                  properties: {}
    post: 
      description: Add new player.
      responses:
        '200':
          description: TODO.
    patch: 
      description: Update a player.
      responses:
        '200':
          description: TODO.
  /v1/rtag:
    get:
      description: Retrieve rTag information.
      responses:
        '200':
          description: TODO.
          content:
            application/json:
              schema:
                items:
                  type: object
                  properties: {}
    post: 
      description: Add new rTag.
      responses:
        '200':
          description: TODO.
    patch: 
      description: Update an rTag.
      responses:
        '200':
          description: TODO.
  /v1/challenge:
    get:
      description: Retrieve challenge information.
      parameters: 
        - name: challengeId
          required: true
          schema: 
            type: string
      responses:
        '200':
          description: TODO.
          content:
            application/json:
              schema:
                items:
                  type: object
                  properties: {}
    post: 
      description: Add new challenge.
      responses:
        '200':
          description: TODO.
    patch: 
      description: Update a challenge.
      responses:
        '200':
          description: TODO.
  /v1/entries:
    get:
      description: Retrieve challenge entry information.
      responses:
        '200':
          description: TODO.
          content:
            application/json:
              schema:
                items:
                  type: object
                  properties: {}
    post: 
      description: Add new challenge entry.
      responses:
        '200':
          description: TODO.
    patch: 
      description: Update an entry.
      responses:
        '200':
          description: TODO.
  /v1/vote:
    get:
      description: Retrieve vote infomation.
      responses:
        '200':
          description: TODO.
          content:
            application/json:
              schema:
                items:
                  type: object
                  properties: {}
    post: 
      description: Add new vote to an object.
      responses:
        '200':
          description: TODO.
    patch: 
      description: Update a vote.
      responses:
        '200':
          description: TODO.